services:
  - type: web
    name: resume-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
