// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdSCRNHQ4tfunBSlpeADAC7iU7cJ5NxRw',
    appId: '1:721639360015:web:2ee327e564a3dbdbca057a',
    messagingSenderId: '721639360015',
    projectId: 'resume-ultrapromax',
    authDomain: 'resume-ultrapromax.firebaseapp.com',
    storageBucket: 'resume-ultrapromax.firebasestorage.app',
    measurementId: 'G-B5SRQWWWHX',
  );
}
